### ISSUE TITLE
Support `attributes` change to json-api specification.

### ISSUE THREAD

**Issue by barelyknown** [eneuhauser/ember-json-api#10]
A [pre-1.0 change was made to the json-api specification regarding resource attributes](https://github.com/json-api/json-api/pull/588).

> ``` json
> {
>   "data": {
>     "type": "articles",
>     "id": "1",
>     "attributes": {
>       // ... attributes of this article
>     }
>   }
> }
> ```

Do you plan on keeping this branch up-to-date with that change?

**Comment by eneuhauser** [comment]
I do plan on updating whenever they release 1.0 or the next release candidate, but as of now, this change is after RC3.

I actually was just about to open this same issue on here because I just noticed the change. What's more, this came up on the project I'm working on. Unfortunately, it's not using JSON API, but I was able to introduce many of the concepts. The issue we ran into is when the PATCH is deserialized into a Java object, there was no way to tell if the attribute was explicitly set to null or if it was omitted. The change to the spec will allow it to be treated as a key/value map rather than an object.

**Comment by barelyknown** [comment]
I agree that it's a good change to the spec. I'm _very_ anxious for the spec to hit 1.0, but I'm still happy that this was introduced.

**Comment by Boubalou** [comment]
We just stumbled upon this as well in our implementation of a Java Backend respecting the latest JSONAPI RC3 spec. 

:+1: on getting this supported before the merge.

**Comment by eneuhauser** [comment]
Just upgraded master to JSON API 1.0.
