### ISSUE TITLE
Question on camelized properties

### ISSUE THREAD

**Issue by brancusi** [eneuhauser/ember-json-api#8]
Hi,

I am working off your latest PR to conform to RC3.

Using JSONAPI Resources with rails.

Getting data in the following format works great, everything gets into the ember-data store:

``` json
{
    "data": [
        {
            "id": "1",
            "name-first": "John",
            "name-last": "Doe",
            "email": "john.doe@boring.test",
            "twitter": null,
            "type": "contacts",
            "links": {
                "self": "http://localhost:3000/contacts/1",
                "phone-numbers": {
                    "self": "http://localhost:3000/contacts/1/links/phone-numbers",
                    "related": "http://localhost:3000/contacts/1/phone-numbers"
                }
            }
        },
        {
            "id": "2",
            "name-first": "Tom",
            "name-last": "Jones",
            "email": "tj@boring.test",
            "twitter": null,
            "type": "contacts",
            "links": {
                "self": "http://localhost:3000/contacts/2",
                "phone-numbers": {
                    "self": "http://localhost:3000/contacts/2/links/phone-numbers",
                    "related": "http://localhost:3000/contacts/2/phone-numbers"
                }
            }
        }
    ]
}
```

Problem is when I try to create a post, it's not switching from camel to dashed case.

Here is what ember is posting on record.save():

``` json
{
    "data": {
        "nameFirst": "Bob",
        "nameLast": "Smoth",
        "email": "bs@nowhere.com",
        "type": "contacts"
    }
}
```

Any ideas?

Thank you

**Comment by eneuhauser** [comment]
CamelCase is the default format. To have it serialize into dashed-case, you can do the following in your serializer:

```
import JsonApiSerializer from 'json-api-serializer';

export default JsonApiSerializer.extend({
  keyForAttribute = function(key) {
    return Ember.String.dasherize(key);
  },
  keyForRelationship = function(key, relationshipKind) {
    return Ember.String.dasherize(key);
  }
});
```

**Comment by jonkoops** [comment]
@eneuhauser The specification recommends the use of the dashterized version. It seems logical to me that this should be the default, as it might confuse users who just want this to work out of the box with their server. 

> ## Recommendations for Naming
> 
> It is recommended that resource types, attribute names, and association names be "dasherized"; i.e. consist of only lower case alphanumeric characters and dashes (U+002D HYPHEN-MINUS, "-").
> 
> It is also recommended that resource types be pluralized. Dasherized and pluralized resource types can be used as URL segments without translation, as discussed below.

Source: http://jsonapi.org/recommendations/#naming

**Comment by eneuhauser** [comment]
@jonkoops, thanks for pointing this out. When I responded, I incorrectly referenced the unit tests on how it's working rather than checking the spec. After your reply, I remembered there was a similar discussion about this earlier from @kurko:

> The spec is not specific about -, so instead of enforcing it right now, may I suggest adding to the README a piece on how to override pathForType to change it from - to snakecase.
> 
> Personally, I'd leave it as snakecase (because AMS, one of the biggest players in the serializers-land uses snakecase) and inform in the README how to change it to -, but that's your choice :smile:

Since the spec is specific about this, should we go with dasherized across the board?

I've created [a new branch with a fix](https://github.com/eneuhauser/ember-json-api/tree/dasherize). I would like another set of eyes on it before I merge it in. Please checkout [my changes](https://github.com/eneuhauser/ember-json-api/compare/master...eneuhauser:dasherize), in particular with regards to `serializeIntoHash`.

**Comment by brancusi** [comment]
Oh this is great. Thank you!

**Comment by jonkoops** [comment]
Yes, I definitely think we should use it as a default.

**Comment by jonkoops** [comment]
I'm a bit busy at the moment, but I'll check out the changes as soon as I've got some spare time.

**Comment by eneuhauser** [comment]
I went ahead and merged it to get more eyes on it. Closing since @brancusi said it fixed his issues.

**Comment by jonkoops** [comment]
@eneuhauser No problem. Sorry I couldn't review the code, had kind of a busy weekend.

**Comment by jonkoops** [comment]
I've [opened an issue](https://github.com/json-api/json-api/issues/583) about the naming conventions in the JSON API spec. I personally believe if we allow different implementations of of this syntax we might end up with a lot of inconsistent APIs we need to consume. I'd appreciate some feedback on this id you guys are able.

_Update: I've closed the issue since there was already a thread discussing something related, see: https://github.com/json-api/json-api/issues/567#issuecomment-99132979_
